### ISSUE TITLE
[feature] add search_agent

### ISSUE THREAD

**Issue by Tata0703** [PathOnAI/LiteWebAgent#40]

**Comment by danni-zhang-loggia** [comment]
https://jykoh.com/search-agents

**Comment by Tata0703** [comment]
https://jykoh.com/search-agents

**Comment by Tata0703** [comment]
Step 1: generate multiple possible actions, with probability score

**Comment by Tata0703** [comment]
Step 2: implement search algorithm: https://github.com/Tata0703/BrowserAgent/blob/main/MCTS/search-agents-main/run_demo.py#L375-L605

**Comment by Tata0703** [comment]
step 1 PR: https://github.com/PathOnAI/LiteWebAgent/pull/49
