### ISSUE TITLE
Error while trying example - state.json

### ISSUE THREAD

**Issue by aksj98** [PathOnAI/LiteWebAgent#51]
When I tried one of the examples : 

`
python -m litewebagent.main --agent_type HighLevelPlanningAgent --starting_url https://www.airbnb.com --goal "set destination as San Francisco, then search the results" --plan "(1) enter the 'San Francisco' as destination, (2) and click search"`

I get the following error:
![image](https://github.com/user-attachments/assets/0f5330c2-fe6b-4b2a-9de1-d5349f5345d6)

The problem seems to be in the browser's context initialization and the state.json required for it

**Comment by Tata0703** [comment]
Hi @aksj98 

Thanks for pointing this out, I have pushed a commit to fix this error: https://github.com/PathOnAI/LiteWebAgent/commit/793b97ce1a76f92fc125281b1fe92fdc182d73bc

The state.json file is used for automating logins on websites, but it's not necessary to get started with this repository. It works by storing login session data after a manual login, which Playwright can then use as a storage state for automatic logins in future runs. However, this functionality isn't currently implemented in the repo and will be added later. You can begin using the basic features of the repository without worrying about this file for now. Thanks!
