### ISSUE TITLE
[feature] fix replay

### ISSUE THREAD

**Issue by danni-z-loggia** [PathOnAI/LiteWebAgent#76]
to pass prompts instead of actions, since action grounding accuracy is very high

**Comment by Tata0703** [comment]
change log folder

**Comment by Tata0703** [comment]
https://github.com/PathOnAI/LiteWebAgent/blob/main/litewebagent/utils/utils.py#L221-L243

**Comment by Tata0703** [comment]
https://github.com/PathOnAI/LiteWebAgent/blob/main/litewebagent/agents/PromptAgents/PromptAgent.py#L83-L86

**Comment by Tata0703** [comment]
https://github.com/PathOnAI/LiteWebAgent/blob/main/litewebagent/utils/utils.py#L221
https://github.com/PathOnAI/LiteWebAgent/blob/main/litewebagent/utils/replay.py#L109
